### PR TITLE
Updated all styles to the BJCP 2015 Style Guide from 2008

### PR DESCRIPTION
**Pull request by couchguy**
Updated the Styles.xml file to be the BJCP 2015 style guide instead of 2008, also updated the gradle packages to no use deprecated libraries.

### CODE REVIEW

**Comment by caseydavenport** [comment]
Thanks! This LGTM.

**Comment by caseydavenport** [comment]
@couchguy are the build.grade changes relevant? If possible could we remove those from the PR?

**Comment by couchguy** [comment]
No, I don't think they are, There are just what I had to change to get it to work with the newest graddle stuff.

**Comment by couchguy** [comment]
Created a new PR without Gradle changes.

**Pull request closed without merging**
